Jupyter.remote.add.connection=添加 Jupyter 连接…
Jupyter.remote.add.dialog.ok.button.text=添加
Jupyter.remote.add.dialog.title=新建 Jupyter 连接
Jupyter.remote.add.option.discovered.local=连接到正在运行的本地 Jupyter 服务器
Jupyter.remote.add.option.managed.local=启动本地 Jupyter 服务器
Jupyter.remote.add.option.url=使用 URL 连接到 Jupyter 服务器
Jupyter.remote.copying=正在将 ''{0}'' 复制到 ''{1}''…
Jupyter.remote.copying.multiple=正在将多个文件复制到 ''{0}''…
Jupyter.remote.failed.to.load.remote=加载远程文件时出错
Jupyter.remote.managed.working.directory.title=Jupyter 工作目录
Jupyter.remote.reconnect=重新连接…
Jupyter.remote.refactoring.rename=重命名
Jupyter.remote.refactoring.rename.directory=重命名目录
Jupyter.remote.refactoring.rename.file=重命名文件
Jupyter.remote.refactoring.rename.notebook=重命名 Notebook
Jupyter.remote.refactoring.renaming.to=将 ''{0}'' 重命名为:
Jupyter.remote.reload.file.from.server.all.files.are.up.to.date=所有文件都处于最新状态
Jupyter.remote.reload.file.from.server.dialog.checkbox.remember.my.choice=记住我的选择(&R)
Jupyter.remote.reload.file.from.server.dialog.question=服务器上存在较新版本的 {0}。是否要用它重写本地副本?
Jupyter.remote.reload.file.from.server.dialog.title=是否用远程文件重写本地文件?
Jupyter.remote.reload.file.from.server.number.of.files.reloaded={0,choice,1#{0} 个文件|2#{0} 个文件}已更新
Jupyter.remote.remove.connection.confirmation=确定要移除与 {0} 的连接吗?
Jupyter.remote.remove.multiple.files=是否删除 {0} 个远程文件?
Jupyter.remote.unable.to.create.target.dir=无法创建目标目录 ''{0}''
Jupyter.remote.unknown.remote.file.status.copying.aborted=无法检查远程 ''{0}'' 文件是否存在。复制过程中止。
Jupyter.remote.url=服务器 URL:
Jupyter.remote.url.discovered.local.combobox=选择正在运行的本地 Jupyter 服务器:
Jupyter.remote.url.discovered.no.servers=<无服务器>
Jupyter.remote.url.managed.local.directory=工作区目录:
Jupyter.remote.verify.cant.create.path=提供的路径无效
Jupyter.remote.verify.managed.empty.path=Jupyter 工作目录不能为空
Jupyter.remote.verify.managed.not.absolute=路径应为绝对路径
Jupyter.remote.verify.managed.not.directory=提供的路径不是目录路径
Jupyter.remote.verify.managed.wrong.path=路径包含错误字符
Jupyter.remote.verify.url.check.cancelled=检查已取消
Jupyter.remote.verify.url.connecting=正在检查 Jupyter 连接…
Jupyter.remote.verify.url.connection.error=连接错误
Jupyter.remote.verify.url.empty=Jupyter URL 不能为空
Jupyter.remote.verify.url.malformed=URL 格式不正确。请提供类似于 http://my.jupyter.org:8888 的 Jupyter URL
Jupyter.remote.verify.url.not.jupyter=无法到达此 URL 后面的 Jupyter 服务器
Jupyter.remote.verify.url.unexpected.error=意外错误
Jupyter.remote.verify.url.wrong.response=Jupyter 连接错误。错误代码: {0}，消息: {1}
action.ReloadRemoteFileAction.description=从服务器重新加载最新更改
action.ReloadRemoteFileAction.text=从服务器重新加载…
notification.group.jupyter.remote=Jupyter 远程 Notebook